/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pop_up_windows;
import models.Aksiologisi;
import javax.swing.JOptionPane;
import java.io.*;
import java.io.FileNotFoundException;


/**
 *
 * @author Pavlos
 */
public class RATE extends javax.swing.JFrame {
    
    String id;
    String name;

    /**
     * Creates new form RATE
     */
    public RATE(String id,String name) {
        initComponents();
        this.jLabel3.setText("You are rating old list id=" + id);
        this.id = id;
        this.name = name;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Rate (/10)");

        jLabel2.setText("Comments");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateRating(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void calculateRating(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateRating
                
        int rating = Integer.parseInt(this.jTextField2.getText());
        String strInfo = null;
        String temp = null;
        int avgRate=0;
        int numberReview=0;
        String newLine[];
        String finalLine;
        String fullText = "";
        try{
        BufferedReader grammi = new BufferedReader(new FileReader("src/magazatores2.txt"));
        grammi.mark(10000);
        
        //Periptwsi pou exei dwsei lathos rating
        if(rating<0 || rating>10)
            JOptionPane.showMessageDialog(null, "Rating was out of bounds");
                                                   
         if(rating>=0 && rating<=10) { 
            Aksiologisi newrate = new Aksiologisi();
            
            //Diavazw tin vathmologia tou magaziou kai ton arithmo apo reviews
             while((strInfo = grammi.readLine()) != null){
                if(name.equals(strInfo.split(",")[0])){
                    avgRate = Integer.parseInt(strInfo.split(",")[6]);
                    numberReview = Integer.parseInt(strInfo.split(",")[7]);
                    temp = strInfo;
                 }
                fullText = fullText.concat(strInfo);
                fullText = fullText.concat("\r\n");
             }
           
                                     
                   //Ypologismos neas vathmologias     
                   avgRate = ((avgRate * numberReview) + rating) / (numberReview+1);
                   numberReview++;
                   newLine = temp.split(",");
                   newLine[6] = String.valueOf(avgRate);
                   newLine[7] = String.valueOf(numberReview);
                   finalLine = String.join(",", newLine);
                                     
                    
                  BufferedWriter writeTable = new BufferedWriter(new FileWriter("src/magazatores2.txt",false));
                  grammi.reset();
                    
                  //Antikathistw to magazi tin nea grammi
                  fullText = fullText.replace(temp, finalLine);
                  
                  //Grafw to neo keimeno magaziwn
                  writeTable.write(fullText);
                  
                  writeTable.close();
                  JOptionPane.showMessageDialog(null, "Rating was successful");
         }
    
                } catch (Exception ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Rating was not successful");
                }
                
                      
    }//GEN-LAST:event_calculateRating

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
